# Generated by Django 2.1.11 on 2019-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichLogApp', '0002_auto_20191007_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='description',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
